services:
  - type: web
    name: mobart
    runtime: static
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_BASE44_APP_ID
        sync: false
      - key: VITE_BASE44_APP_BASE_URL
        sync: false
      - key: VITE_GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_DRIVE_ORDER_FILES_FOLDER_ID
        sync: false
      - key: VITE_GOOGLE_DRIVE_AVATARS_FOLDER_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
